[package]
name = "rrdb"
version = "0.0.0" 
authors = ["myyrakle <sssang97@naver.com>"] 
description = "ready" 
keywords = ["db", "database", "sql"] 
edition = "2018" 
license = "MIT" 
include = ["src/main", "src/lib", "Cargo.toml"]
exclude = []
readme = "README.md" 
repository = "https://github.com/myyrakle/rrdb"
documentation = "https://github.com/myyrakle/rrdb/blob/master/README.md"
homepage = "https://github.com/myyrakle/rrdb/blob/master/README.md"

[dependencies]
tokio = { version = "1", feature = ["full"] }

[[bin]]
name = "run"
path = "./src/main.rs"